title: Krishnagopal Halder
description: "Research Scientist | Geospatial AI | Remote Sensing | Agricultural Modelling"
logo: /assets/img/headshot_circle.png
#description: text below image
show_downloads: true
baseurl: "" 
url: "https://geonextgis.github.io"
theme: jekyll-theme-minimal


author:
  name   : "Krishnagopal Halder"
  avatar : "/assets/images/profile.jpg"
  bio    : "Research Scientist at ZALF. Focused on AI for Agriculture, Remote Sensing, and Geospatial Analysis."
  location : "Müncheberg, Brandenburg, Germany"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:Krishnagopal.Halder@zalf.de"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/geonextgis"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/krishnagopal-halder"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=b02pfFMAAAAJ&hl=en&authuser=2"
    - label: "Medium"
      icon: "fab fa-medium"
      url: "https://medium.com/@geonextgis"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap